# Generated by Django 3.0.4 on 2020-03-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='extras',
        ),
    ]
