# Generated by Django 3.0.4 on 2020-03-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_discount_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionfooditem',
            old_name='extra',
            new_name='extras',
        ),
    ]
