# Generated by Django 3.0.4 on 2020-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('WAITER', 'Waiter'), ('KITCHEN', 'Kitchen'), ('MANAGER', 'Manager')], default='MANAGER', max_length=10),
        ),
    ]
